---
title: "Data Science Math Skills"
author: "Katherine G. Pe"
output:
  pdf_document:
    toc: yes
    toc_depth: 3
  html_document:
    highlight: pygments
    theme: spacelab
    toc: yes
urlcolor: blue
---

$\pagebreak$


# Data Science Math Skills

## Course Information

Data Science Math Skills by **Duke University** is a online course you can take on this site  [Coursera](https://www.coursera.org/learn/datasciencemathskills).


## Motivation for Learning & Re-learning

A lot of graduate school students struggle with Data Science courses only because of their lack of knowledge and/or understanding of Mathematics for Data Science. The course gives an overview of Mathematical concepts you will encounter while learning Data Science.


## Supplemental Notes and Videos

Here's how I make my notes:

My notes include videos from Khan Academy and other websites. The content's the same, and often a bit better due to lack of errors. The text are usually from the Coursera video transcripts.

I indicate **why** it is important to learn such concepts through **Further Reading** notes.


## Sets and What They're Good For



### Set Basics and Vocabulary

* [Set Theory](https://plato.stanford.edu/entries/set-theory/)
* [Set Theory Operations](https://brilliant.org/wiki/set-theory/)


#### Further Reading

> A set is the fundamental discrete structure on which all other discrete structures are built.

Those who studied Discrete Mathematics or read a book about it will probably just re-learn a lot from this course on Set Basics.

* [Applications of Set Theory in Computer Science](https://www.quora.com/What-are-the-applications-of-set-theory-in-computer-science/answer/Joshua-Gross-8) - A list of the most obvious applications of Set Theory.
* [Discrete Mathematics and Its Applications](https://www.amazon.com/Discrete-Mathematics-Applications-Kenneth-Rosen/dp/0072899050) - I read most of the book as a supplemental material for a Discrete Math course. The book clearly states why a set is the foundational structure in Computer Science.


### Venn Diagrams

* [What are Venn diagrams?](https://www.bbc.co.uk/education/guides/zt7rk7h/revision)


#### Further Reading

* [A Visual Explanation of SQL Joins](https://blog.codinghorror.com/a-visual-explanation-of-sql-joins/)



## The Infinite World of Real Numbers

* [What are Real Numbers?](https://www.youtube.com/watch?v=3YwrcJxEbZw)
* [Multi-step Inequalities](https://www.khanacademy.org/math/algebra/one-variable-linear-inequalities/multi-step-inequalities/v/multi-step-inequalities)



## The Jagged S Symbol

* [Sigma/Summation Notation](http://www.columbia.edu/itc/sipa/math/summation.html)

    $\sum_{n=1}^{10} n^{2}$

* The Sigma has similarities to the [factorial](https://www.khanacademy.org/math/precalculus/prob-comb/combinatorics-precalc/v/zero-factorial-or-0) symbol, but it suggests that you add the values of *i* based on the stopping point *n*


### Further Reading

* [Graph-based Machine Learning](https://blog.insightdatascience.com/graph-based-machine-learning-6e2bd8926a0)


## Descartes Was Really Smart

### Plotting Points

* The x-axis is going to be the set of all points x-y in the Cartesian plane, x-y in R2, such that their y coordinate is zero.

* We divide the Cartesian plane into four separate regions, and these we call **quadrants**.

* [Coordinate plane: quadrants](https://www.youtube.com/watch?v=1op92ojA6q0)

### Distance Formula

* [Distance formula](http://www.ccimath.ca/distance-formula.html)

    $d = \sqrt{ (x_2-x_1)^2 + (y_2-y_1)^2 }$


### Point-Slope Formula for Lines

* [Point Slope Form](https://www.khanacademy.org/math/algebra/two-var-linear-equations/point-slope/a/point-slope-form-review)

    $y-b=m(x-a)$

* [Calculating the Slope](http://cls.syr.edu/mathtuneup/grapha/Unit4/Unit4a.html)

    $(y2-y1/x2-x1)$



### Slope-Intercept Formula

* [Slope Intercept Equation](https://www.khanacademy.org/math/algebra/two-var-linear-equations/point-slope/v/point-slope-and-slope-intercept-form-from-two-points)

* [Intro to Slope Intercept Form](https://www.khanacademy.org/math/algebra/two-var-linear-equations/slope-intercept-form/a/introduction-to-slope-intercept-form)

    $y=mx+b$



## Input-Output Machines


### Functions: Mapping from Sets to Sets

* [Functions on Sets - UCLA](http://www.math.ucla.edu/~radko/circles/lib/data/Handout-759-870.pdf)

    $f: A \rightarrow B$


### Functions: Graphing in the Cartesian Plane

* [Functions on a Coordinate Plane](https://www.ck12.org/algebra/functions-on-a-coordinate-plane/lesson/Functions-on-a-Cartesian-Plane-BSC-ALG/)

* [Vertical line test](https://en.wikipedia.org/wiki/Vertical_line_test)

* The **vertical line** test says: *any vertical line, intersects the graph of a function once*. If it intersects it more than once, we violate things here.


### Increasing and Decreasing Functions

* A function is increasing whenever:

    $a < b$

    $f(a) < f(b)$

    $f(x) = 2^x - \text{An example of an increasing function}$

* A function is decreasing whenever:

    $a > b$

    $f(a) > f(b)$

    $g(x) = 3^{-x} - \text{An example of a decreasing function}$


### Composition and Inverse

* [How to find the inverse of a composite function](https://math.stackexchange.com/questions/59929/how-to-find-inverse-of-a-composite-function)
* [Evaluating Composite functions](https://www.youtube.com/watch?v=oORnGaJp1pk)
* Not every function has an inverse.
* If the graph of *f* fails the *horizontal line test*, the graph has no inverse.


## This is about that derivative stuff


### Tangent Lines - Slope of a Graph at a Point

* [How to find the slope & equation of tangent line at a given point](https://www.youtube.com/watch?v=Uataz2hvNks)
* [Finding the Equation Of A Tangent Line](http://gato-docs.its.txstate.edu/slac/Subject/Math/Calculus/Findting-the-Equation-of-a-Tangent-Line/Finding)
* A **Tangent Line** is a line which locally touches a curve at one and only one point.
* Formulas:

    $f'(a)$

### Tangent Lines - The Derivative Function

* [The derivative & tangent line equations](https://www.khanacademy.org/math/ap-calculus-ab/ab-derivative-intro/ab-linearity/v/derivative-as-slope-of-tangent-line)
* Formulas:

    $f'(x) = 2x$

    $f(x) = x^{2}$


## Fast Growth, Slow Growth


### Using Integer Exponents

* 0 as an exponent:

    $2^{0}=1$

* Negative exponents:

    $x^{-n}=1/x^{n}$

* [Scientific Notation](https://www.youtube.com/watch?v=WwmJ5nMmigQ)


### Simplification Rules for Algebra using Exponents

* Multiplication rule

    $x^{n}x^{m} = x^{(n+m)}$

* Power to a power

    $(x^{n})m = x^{nm}$

* Product to a power

    $(xy)^{n} = x^{n}y^{n}$

* Fraction to a power

    $\frac{x}{y}^{n} = \frac{x^{n}}{y^{n}}$

* Division and negative powers

    $\frac{x^{n}}{x^{n}} = x^{n-m}$

* Fractional exponents

    $x^{(\frac{a}{b})} = ^{b} \sqrt{x^{a}}$


### How Logarithms & Exponents are Related

* [Intro to logarithms](https://www.khanacademy.org/math/algebra2/exponential-and-logarithmic-functions/introduction-to-logarithms/v/logarithms)

* Exponential form:

    $b^{x} = N$

* Logarithmic form:

    $x=log_{b} = N$

* The logarithm of any base of 1 is 0, just as any number raised to 0 is 1.

* [Solving Logarithmic Equations](https://www.youtube.com/watch?v=BxD6ZFbu01c): This video was more helpful in understanding how to solve for *x* on a Logarithmic equation problem.


#### General rules

* Product rule

    $log(xy) = log(x) + log(y)$

* Quotient rule

    $log\frac{x}{y}  = log(x) - log(y)$


* Power and root rule

    $log(x^{n}) = n log(x)$

#### Further Reading

* One of the most popular concepts in Data Science is in its logarthmic form (*ln*): [Logistic Regression](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/BS704_Multivariable/BS704_Multivariable8.html)

* Watch more about [Simple Logistic Regression](https://www.youtube.com/watch?v=_Po-xZJflPM)

### Change of Base


* The base of **10**, **2** and the natural log *(e)* are common in Data Science.

* Formula for changing the base:

    $log_{a}(b) = \frac{log_{x}(b)}{log_{x}(a)}$

### The Rate of Growth of Continuous Processes

* Exponential rate of growth can be a **discrete** exponential rate of growth or a **continuous** exponential rate of growth.

* Note: those who studied Finance will likely see the practicality of knowing, but not of the terms of themselves.

* Discrete rate of growth:

    $1.00(1 + r)t$

* [Euler's contstant *e*](https://en.wikipedia.org/wiki/E_(mathematical_constant))

* What is *e*?

    $2.71828$

* Euler is pronounced *Oyler*. He's a mathematician most famously known of his solution to the graph theory problem: [Seven Bridges of Königsberg](https://en.wikipedia.org/wiki/Seven_Bridges_of_K%C3%B6nigsberg)

* Problem: A baby elephant weighing 200 kg grows at a continuously compounded rate of 5%/year. How much does it weigh in 3 years?

    $(200 kg)e^{(0.05)(3)} = 232.4 kg$


## Basic Probability Definitions

### Probability Definitions and Notation

#### Definition

* Probability is the degree of belief in the truth or falsity of a statement.
* When I am certain that a statement is true then that statement is assigned probability **1** and if I'm certain the statement is false,
 then it's assigned probability is **0**.


#### Notation

* The probability of x:

    $P(x)$

* The negation of statement x:

    $~x$

#### Law of excluded middle

* Probability of a statement and the probability of the negation of a statement must sum to 1.

    $P(x) + P(~x) = 0$

#### Principle of indifference

* For the *i-th* outcome *xi* in a distribution with *n* possible outcomes.


    $P_{xi} = \frac{1}{n}$


    $P\text{(event)} = \frac{\text{number of outcomes as defined in event}}{\text{total number of possible outcomes in universe}}$

### Permutations and Combinations

#### Permutations

* Order matters
* Example:

    $\text{placing five people in five different positions: 120 ways}$

* [Permutations](https://www.youtube.com/watch?v=XqQTXW7XfYA)

* Formula:

    $\frac{n!}{(n - m)!}$


#### Combinations

* Order does not matter
* Example:

    $\text{forming a five-person team from five people: 1}$


* [Combinations](https://www.youtube.com/watch?v=iKy-d5_erhI)

* Formula:

    $\frac{n!}{r! (n - r)}$

#### Replacement

* Sampling *with replacement* (independent), e.g. drawing a card and putting it back in the deck

* Sampling *without replacement*, e.g. drawing a card from a deck and not putting it back
